# Defaults

defaults: &defaults
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: localhost
  username: root

production_defaults: &production_defaults
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: localhost

# Development

development:
  database: wrektranet_development
  <<: *defaults

staff_legacy_development:
  database: staff_legacy_development
  <<: *defaults

# This is a dummy since oracle can't easily be reproduced on your end.
# If you need to test things out, you have to connect to the production database.
# Please be careful!
oracle_legacy_development:
  database: oracle_legacy_development
  <<: *defaults

# Test

test: &test
  database: wrek_test
  username: root
  <<: *defaults

staff_legacy_test:
  database: staff_legacy_test
  username: root
  <<: *defaults

# Production

production:
  database: wrektranet_production
  <<: *production_defaults

staff_legacy_production:
  database: staff
  <<: *production_defaults

# Optional, Oracle database for music and automation
oracle_legacy_production:
  adapter: oracle_enhanced
  host: localhost
  database: db
  username: username
  password: password
