# Defaults

defaults: &defaults
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: localhost

production_defaults: &production_defaults
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: localhost
  username: root
  password: root

# Development

development:
  database: wrektranet_development
  <<: *defaults

staff_legacy_development:
  database: staff_legacy_development
  <<: *defaults

# Test

test: &test
  database: wrek_test
  <<: *defaults

staff_legacy_test:
  database: staff_legacy_test
  <<: *defaults

# Production

production:
  database: wrektranet_production
  <<: *production_defaults

staff_legacy_production:
  database: staff
  <<: *production_defaults